### ISSUE TITLE
babel-eslint has been deprecated

### ISSUE THREAD

**Issue by byoungd** [worldzhao/rush-monorepo-example#1]
babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

Any update for `features/eslint-config`?

**Comment by worldzhao** [comment]
> babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
> 
> Any update for `features/eslint-config`?

I just chose a better looking [eslint preset configuration](https://www.npmjs.com/package/eslint-config-ali) for this template, but have no idea to maintain it, the only difference is the addition of the [rush patch](https://www.npmjs.com/package/@rushstack/eslint-patch).

And more developers are used to change to their own eslint preset configuration, there might be better eslint preset recommendations, do you have any ideas?

**Comment by worldzhao** [comment]
把依赖全部升级了一遍，优化了一下结构，现在这个问题不存在了，eslint-config 也直接用的 eslint-config-react-app，有问题随时沟通哈。

**Comment by byoungd** [comment]
> 把依赖全部升级了一遍，优化了一下结构，现在这个问题不存在了，eslint-config 也直接用的 eslint-config-react-app，有问题随时沟通哈。

Thanks a lot!
